name: 'Generate PHP project classes list file'
description: 'GitHub action to generate a file with PHP project classes list (works only with composer projects)'

branding:
  icon: list
  color: blue

inputs:
  output_file:
    description: File where will be written classes list
    required: true
  project_path:
    description: Path to the directory containing composer.json (default is current directory)
    required: false
    default: '.'

runs:
  using: 'node20'
  main: 'dist/index.js'
